#Requires -Version 5.1
<#
.SYNOPSIS
    SQLLabBuilder Centralized configuration.
    Single source of truth for all names, IPs, passwords, domain info, and paths.
    All step scripts dot-source this file. No magic strings in step files.

IDEMPOTENCY: Password fields are blank on initial install.
    00-Preflight.ps1 generates passwords and patches this file once.
    On subsequent runs the existing values are preserved.
#>

#region Paths — set by 01-SelectDrive.ps1 at runtime
$LabRoot        = "D:\SQLLabBuilder"   # e.g. D:\SQLLabBuilder
$ISOPath        = "D:\SQLLabBuilder\ISOs"   # $LabRoot\ISOs
$VMPath         = "D:\SQLLabBuilder\VMs"   # $LabRoot\VMs
$LogPath        = "D:\SQLLabBuilder\logs"   # $LabRoot\logs
$CheckpointPath = "D:\SQLLabBuilder\logs\checkpoints"   # $LabRoot\logs\checkpoints
#endregion

#region Network
$SwitchName   = "SQLLabSwitch"
$NatName      = "SQLLabNAT"
$LabSubnet    = "192.168.100.0"
$LabPrefix    = 24
$HostIP       = "192.168.100.1"
$DCStaticIP   = "192.168.100.10"
$SQL1StaticIP = "192.168.100.11"
$SQL2StaticIP = "192.168.100.12"
$ClusterIP    = "192.168.100.20"
$ListenerIP   = "192.168.100.30"
$Gateway      = "192.168.100.1"
#endregion

#region Domain
$DomainName  = "sqllab.local"
$NetBIOSName = "SQLLAB"
#endregion

#region VM / Computer Names
$DCVMName    = "SQLLab-DC"
$SQL1VMName  = "SQLLab-SQL1"
$SQL2VMName  = "SQLLab-SQL2"

$DCComputerName   = "SQLLAB-DC"
$SQL1ComputerName = "SQLLAB-SQL1"
$SQL2ComputerName = "SQLLAB-SQL2"
#endregion

#region Cluster / AG
$ClusterName  = "SQLLabCluster"
$AGName       = "SQLLabAG"
$ListenerName = "SQLLabListener"
$ListenerPort = 1433
$EndpointPort = 5022
$TestDatabase = "AGTestDB"
$AGShareName  = "AGShare"
$WitnessShare = "ClusterWitness"
#endregion

#region SQL Service Account
$SQLSvcAccountName = "sqlsvc"
$SQLSvcAccount     = "SQLLAB\sqlsvc"
#endregion

#region ISO file names — target names used throughout all steps
$WinServerISOName = "WinServer2025.iso"
$SQL2019ISOName   = "SQLServer2019-dev.iso"
$SQL2022ISOName   = "SQLServer2022-dev.iso"
$SQL2025ISOName   = "SQLServer2025-dev.iso"
#endregion

#region ISO download URLs
# If a link breaks, find current Developer edition bootstrappers at:
#   WS2025  : https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2025
#   SQL Dev : https://www.microsoft.com/en-us/sql-server/sql-server-downloads
#
# Windows Server 2025 — direct ISO download (64-bit, English)
$WinServer2025ISOUrl    = "https://go.microsoft.com/fwlink/p/?linkid=2195280"
# SQL Server Developer Edition — small bootstrapper EXEs (~4 MB); step 02 runs them with
#   /ACTION=Download /QUIET /IACCEPTSQLSERVERLICENSETERMS /EDITION=Developer /MEDIAPATH=... /MEDIATYPE=ISO
# to pull the full Developer ISO without any interactive GUI.
$SQL2019BootstrapperUrl = "https://download.microsoft.com/download/d/a/2/da259851-b941-459d-989c-54a18a5d44dd/SQL2019-SSEI-Dev.exe"
$SQL2022BootstrapperUrl = "https://download.microsoft.com/download/c/c/9/cc9c6797-383c-4b24-8920-dc057c1de9d3/SQL2022-SSEI-Dev.exe"
$SQL2025BootstrapperUrl = "https://go.microsoft.com/fwlink/?linkid=2344711&clcid=0x409&culture=en-us&country=us"
#endregion

#region Passwords — auto-generated by 00-Preflight.ps1 on first run; do not edit manually
$AdminPassword             = "SqlLab2025!"
$SQLServiceAccountPassword = "SqlLab2025!"
$SAPassword                = "SqlLab2025!"
$LabAdminPassword          = "SqlLab2025!"
#endregion

#region Lab access accounts
# SQL auth login created on both SQL nodes — use this to connect via the listener or any node.
# For listener connections from a non-domain client, SQL auth is the only reliable method.
# (Listener requires Kerberos for Windows auth; use runas /netonly for Windows auth instead.)
$LabAdminUser = "labadmin"
#endregion

#region Cluster contexts — primary + additional (add-cluster) AGs
# The lab can host more than one independent 2-node Always On AG, each on its own
# Windows Failover Cluster but sharing the single domain controller, virtual switch
# and NAT. Get-LabClusterContext returns everything a build needs for a given
# 1-based cluster index:
#
#   Index 1  = the primary cluster. Returns EXACTLY the values defined above, so the
#              original build (steps 04-15) is byte-for-byte unchanged.
#   Index N>1 = an add-cluster AG. Names and IPs are derived from N so any number of
#              clusters can coexist without collisions (RAM permitting).
#
# IP layout on the lab /24 (base derived from the DC's subnet so it survives the
# preflight subnet-conflict auto-adjust):
#   .10 DC   .11/.12 primary nodes   .20 primary cluster   .30 primary listener
#   Cluster N>1 gets a 10-address block starting at .40:  block = 40 + (N-2)*10
#     nodes  = block+1, block+2     cluster = block+5     listener = block+8
function Get-LabClusterContext {
    param([Parameter(Mandatory)][int]$Index)

    if ($Index -lt 1) { throw "Cluster index must be >= 1 (got $Index)." }

    if ($Index -eq 1) {
        return @{
            Index         = 1
            IsPrimary     = $true
            Node1VMName   = $SQL1VMName
            Node2VMName   = $SQL2VMName
            Node1Computer = $SQL1ComputerName
            Node2Computer = $SQL2ComputerName
            Node1IP       = $SQL1StaticIP
            Node2IP       = $SQL2StaticIP
            ClusterName   = $ClusterName
            ClusterIP     = $ClusterIP
            AGName        = $AGName
            ListenerName  = $ListenerName
            ListenerIP    = $ListenerIP
            WitnessShare  = $WitnessShare
            HostsMarker   = "# SQLLabBuilder"     # matches existing base hosts block
            CpSuffix      = ""
        }
    }

    # Derive the subnet base (first three octets) from the DC IP so we honor any
    # subnet that the preflight step auto-selected to avoid a conflict.
    $subnetBase = ($DCStaticIP -split '\.')[0..2] -join '.'
    $block      = 40 + ($Index - 2) * 10
    if (($block + 8) -gt 254) {
        throw "Cluster index $Index would exceed the lab /24 address range. Use a lower index."
    }

    # Node numbering continues past the primary pair: cluster N uses SQL(2N-1)/SQL(2N).
    $n1 = (2 * $Index) - 1
    $n2 = (2 * $Index)

    return @{
        Index         = $Index
        IsPrimary     = $false
        Node1VMName   = "SQLLab-SQL$n1"
        Node2VMName   = "SQLLab-SQL$n2"
        Node1Computer = "SQLLAB-SQL$n1"
        Node2Computer = "SQLLAB-SQL$n2"
        Node1IP       = "$subnetBase.$($block + 1)"
        Node2IP       = "$subnetBase.$($block + 2)"
        ClusterName   = "SQLLabCluster$Index"
        ClusterIP     = "$subnetBase.$($block + 5)"
        AGName        = "SQLLabAG$Index"
        ListenerName  = "SQLLabListener$Index"
        ListenerIP    = "$subnetBase.$($block + 8)"
        WitnessShare  = "ClusterWitness$Index"
        HostsMarker   = "# SQLLabBuilder-c$Index"
        CpSuffix      = "-c$Index"
    }
}
#endregion
















