#Requires -Version 5.1
<#
.SYNOPSIS
    SQLLabBuilder — Centralized configuration.
    Single source of truth for all names, IPs, passwords, domain info, and paths.
    All step scripts dot-source this file. No magic strings in step files.

IDEMPOTENCY: Password fields are blank on initial install.
    00-Preflight.ps1 generates passwords and patches this file once.
    On subsequent runs the existing values are preserved.
#>

#region Paths — set by 01-SelectDrive.ps1 at runtime
$LabRoot        = "D:\SQLLabBuilder"   # e.g. D:\SQLLabBuilder
$ISOPath        = "D:\SQLLabBuilder\ISOs"   # $LabRoot\ISOs
$VMPath         = "D:\SQLLabBuilder\VMs"   # $LabRoot\VMs
$LogPath        = "D:\SQLLabBuilder\logs"   # $LabRoot\logs
$CheckpointPath = "D:\SQLLabBuilder\logs\checkpoints"   # $LabRoot\logs\checkpoints
#endregion

#region Network
$SwitchName   = "SQLLabSwitch"
$NatName      = "SQLLabNAT"
$LabSubnet    = "192.168.100.0"
$LabPrefix    = 24
$HostIP       = "192.168.100.1"
$DCStaticIP   = "192.168.100.10"
$SQL1StaticIP = "192.168.100.11"
$SQL2StaticIP = "192.168.100.12"
$ClusterIP    = "192.168.100.20"
$ListenerIP   = "192.168.100.30"
$Gateway      = "192.168.100.1"
#endregion

#region Domain
$DomainName  = "sqllab.local"
$NetBIOSName = "SQLLAB"
#endregion

#region VM / Computer Names
$DCVMName    = "SQLLab-DC"
$SQL1VMName  = "SQLLab-SQL1"
$SQL2VMName  = "SQLLab-SQL2"

$DCComputerName   = "SQLLAB-DC"
$SQL1ComputerName = "SQLLAB-SQL1"
$SQL2ComputerName = "SQLLAB-SQL2"
#endregion

#region Cluster / AG
$ClusterName  = "SQLLabCluster"
$AGName       = "SQLLabAG"
$ListenerName = "SQLLabListener"
$ListenerPort = 1433
$EndpointPort = 5022
$TestDatabase = "AGTestDB"
$AGShareName  = "AGShare"
$WitnessShare = "ClusterWitness"
#endregion

#region SQL Service Account
$SQLSvcAccountName = "sqlsvc"
$SQLSvcAccount     = "SQLLAB\sqlsvc"
#endregion

#region ISO file names — target names used throughout all steps
$WinServerISOName = "WinServer2025.iso"
$SQL2022ISOName   = "SQLServer2022-eval.iso"
$SQL2025ISOName   = "SQLServer2025-eval.iso"
#endregion

#region ISO download URLs
# If a link breaks, find the current one at the Microsoft Evaluation Center pages:
#   WS2025  : https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2025
#   SQL 2022: https://www.microsoft.com/en-us/evalcenter/evaluate-sql-server-2022
#   SQL 2025: https://www.microsoft.com/en-us/evalcenter/evaluate-sql-server-2025
#
# Windows Server 2025 — direct ISO download (64-bit, English)
$WinServer2025ISOUrl    = "https://go.microsoft.com/fwlink/p/?linkid=2195280"
# SQL Server — small bootstrapper EXEs (~4 MB); step 02 runs them silently with
#   /ACTION=Download /QUIET /IACCEPTSQLSERVERLICENSETERMS /MEDIAPATH=... /MEDIATYPE=ISO
# to pull the full eval ISO without any interactive GUI.
$SQL2022BootstrapperUrl = "https://go.microsoft.com/fwlink/p/?linkid=2215158&clcid=0x409&culture=en-us&country=us"
$SQL2025BootstrapperUrl = "https://go.microsoft.com/fwlink/p/?linkid=2263661&clcid=0x409&culture=en-us&country=us"
#endregion

#region Passwords — auto-generated by 00-Preflight.ps1 on first run; do not edit manually
$AdminPassword             = "tDQz_+oG%GAY6(o+PT"
$SQLServiceAccountPassword = "hoq(hXHLbu+!e0DrV#"
$SAPassword                = "bKMN)7HtZ5cZ5W9Ex+"
$LabAdminPassword          = "bKMN)7HtZ5cZ5W9Ex+"
#endregion


