#Requires -Version 5.1
<#
.SYNOPSIS
    SQLLabBuilder — Centralized configuration.
    Single source of truth for all names, IPs, passwords, domain info, and paths.
    All step scripts dot-source this file. No magic strings in step files.

IDEMPOTENCY: Password fields are blank on initial install.
    00-Preflight.ps1 generates passwords and patches this file once.
    On subsequent runs the existing values are preserved.
#>

#region Paths — set by 01-SelectDrive.ps1 at runtime
$LabRoot        = ""   # e.g. D:\SQLLabBuilder
$ISOPath        = ""   # $LabRoot\ISOs
$VMPath         = ""   # $LabRoot\VMs
$LogPath        = ""   # $LabRoot\logs
$CheckpointPath = ""   # $LabRoot\logs\checkpoints
#endregion

#region Network
$SwitchName   = "SQLLabSwitch"
$NatName      = "SQLLabNAT"
$LabSubnet    = "192.168.100.0"
$LabPrefix    = 24
$HostIP       = "192.168.100.1"
$DCStaticIP   = "192.168.100.10"
$SQL1StaticIP = "192.168.100.11"
$SQL2StaticIP = "192.168.100.12"
$ClusterIP    = "192.168.100.20"
$ListenerIP   = "192.168.100.30"
$Gateway      = "192.168.100.1"
#endregion

#region Domain
$DomainName  = "sqllab.local"
$NetBIOSName = "SQLLAB"
#endregion

#region VM / Computer Names
$DCVMName    = "SQLLab-DC"
$SQL1VMName  = "SQLLab-SQL1"
$SQL2VMName  = "SQLLab-SQL2"

$DCComputerName   = "SQLLAB-DC"
$SQL1ComputerName = "SQLLAB-SQL1"
$SQL2ComputerName = "SQLLAB-SQL2"
#endregion

#region Cluster / AG
$ClusterName  = "SQLLabCluster"
$AGName       = "SQLLabAG"
$ListenerName = "SQLLabListener"
$ListenerPort = 1433
$EndpointPort = 5022
$TestDatabase = "AGTestDB"
$AGShareName  = "AGShare"
$WitnessShare = "ClusterWitness"
#endregion

#region SQL Service Account
$SQLSvcAccountName = "sqlsvc"
$SQLSvcAccount     = "SQLLAB\sqlsvc"
#endregion

#region ISO URLs
# NOTE: Microsoft evaluation ISO URLs change periodically.
# If a download fails after all retries, visit the evaluation center linked below,
# manually place the ISO at the expected path ($ISOPath), and re-run.
#
#   Windows Server 2025: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2025
#   SQL Server 2022:     https://www.microsoft.com/en-us/evalcenter/evaluate-sql-server-2022
#   SQL Server 2025:     https://www.microsoft.com/en-us/evalcenter/evaluate-sql-server-2025
$WinServerISOUrl = "https://go.microsoft.com/fwlink/p/?LinkID=2195280&clcid=0x409&culture=en-us&country=US"
$SQL2022ISOUrl   = "https://go.microsoft.com/fwlink/p/?linkid=2215158&clcid=0x409&culture=en-us&country=US"
$SQL2025ISOUrl   = "https://go.microsoft.com/fwlink/p/?linkid=2263477&clcid=0x409&culture=en-us&country=US"

$WinServerISOName = "WinServer2025.iso"
$SQL2022ISOName   = "SQLServer2022.iso"
$SQL2025ISOName   = "SQLServer2025.iso"
#endregion

#region Passwords — auto-generated by 00-Preflight.ps1 on first run; do not edit manually
$AdminPassword             = ""
$SQLServiceAccountPassword = ""
$SAPassword                = ""
$LabAdminPassword          = ""
#endregion
